import { useState } from "react";
import { motion } from "framer-motion";
import { Sparkles, Lock, Download } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { Link } from "react-router-dom";

const Strategy = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [artistName, setArtistName] = useState("");
  const [genre, setGenre] = useState("");
  const [currentFollowing, setCurrentFollowing] = useState("");
  const [activePlatforms, setActivePlatforms] = useState("");
  const [biggestGoal, setBiggestGoal] = useState("");
  const [upcomingReleases, setUpcomingReleases] = useState("");
  const [targetAudience, setTargetAudience] = useState("");
  const [budget, setBudget] = useState("");
  const [generating, setGenerating] = useState(false);
  const [plan, setPlan] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!artistName || !genre || !biggestGoal) return;
    setGenerating(true);
    setPlan(null);

    try {
      const { data, error } = await supabase.functions.invoke("generate-strategy", {
        body: { artistName, genre, currentFollowing, activePlatforms, biggestGoal, upcomingReleases, targetAudience, budget },
      });
      if (error) throw error;
      setPlan(data.plan);
      toast({ title: "Strategy generated! 🚀" });
    } catch {
      setPlan("Unable to generate strategy right now. Please try again later.");
      toast({ title: "Generation failed", variant: "destructive" });
    } finally {
      setGenerating(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!plan) return;
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`
      <html><head><title>30-Day Marketing Strategy — ${artistName}</title>
      <style>body{font-family:sans-serif;padding:40px;max-width:800px;margin:0 auto;line-height:1.6}h1{color:#D4AF37}h2{border-bottom:1px solid #eee;padding-bottom:8px}pre{white-space:pre-wrap;font-family:sans-serif}</style>
      </head><body><h1>30-Day Marketing Strategy</h1><h2>${artistName} — ${genre}</h2><pre>${plan}</pre>
      <p style="color:#999;margin-top:40px">Generated by Fully Governed AI Strategy Tool</p>
      </body></html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="min-h-screen bg-background pb-20 md:pb-0">
      <Navbar />
      <div className="grain-overlay" />
      <div className="container pt-24 pb-16 space-y-12">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center">
          <p className="font-mono text-xs tracking-[0.3em] text-primary mb-2 uppercase">AI-Powered</p>
          <h1 className="font-bebas text-5xl md:text-7xl text-foreground tracking-wider">MARKETING STRATEGY</h1>
          <p className="text-muted-foreground font-barlow mt-2 max-w-xl mx-auto">
            Get a personalised 30-day marketing plan powered by AI. Tailored to your genre, goals, and audience.
          </p>
        </motion.div>

        {!user ? (
          <div className="max-w-lg mx-auto text-center py-12">
            <Lock className="w-16 h-16 text-muted-foreground mx-auto mb-4" />
            <p className="text-muted-foreground font-barlow text-lg mb-4">Sign in to access the AI Strategy Tool.</p>
            <Link to="/auth"><Button className="font-bebas text-lg tracking-wider px-8 h-12">SIGN IN</Button></Link>
          </div>
        ) : (
          <div className="max-w-2xl mx-auto space-y-8">
            <div className="bg-card border border-border rounded-lg p-6 space-y-4">
              <h2 className="font-bebas text-2xl text-foreground tracking-wider">YOUR DETAILS</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label className="text-muted-foreground">Artist / Brand Name *</Label>
                  <Input value={artistName} onChange={(e) => setArtistName(e.target.value)} className="mt-1 bg-background" placeholder="e.g. KingBlvck" />
                </div>
                <div>
                  <Label className="text-muted-foreground">Genre / Niche *</Label>
                  <Input value={genre} onChange={(e) => setGenre(e.target.value)} className="mt-1 bg-background" placeholder="e.g. UK Drill, R&B, Afrobeats" />
                </div>
                <div>
                  <Label className="text-muted-foreground">Current Following</Label>
                  <Input value={currentFollowing} onChange={(e) => setCurrentFollowing(e.target.value)} className="mt-1 bg-background" placeholder="e.g. 2k Instagram, 500 Spotify" />
                </div>
                <div>
                  <Label className="text-muted-foreground">Active Platforms</Label>
                  <Input value={activePlatforms} onChange={(e) => setActivePlatforms(e.target.value)} className="mt-1 bg-background" placeholder="e.g. Instagram, TikTok, Spotify" />
                </div>
                <div>
                  <Label className="text-muted-foreground">Upcoming Releases</Label>
                  <Input value={upcomingReleases} onChange={(e) => setUpcomingReleases(e.target.value)} className="mt-1 bg-background" placeholder="e.g. Single in 2 weeks" />
                </div>
                <div>
                  <Label className="text-muted-foreground">Target Audience</Label>
                  <Input value={targetAudience} onChange={(e) => setTargetAudience(e.target.value)} className="mt-1 bg-background" placeholder="e.g. 18-25, South London" />
                </div>
                <div>
                  <Label className="text-muted-foreground">Budget</Label>
                  <Input value={budget} onChange={(e) => setBudget(e.target.value)} className="mt-1 bg-background" placeholder="e.g. £200/month" />
                </div>
              </div>
              <div>
                <Label className="text-muted-foreground">Biggest Goal *</Label>
                <textarea value={biggestGoal} onChange={(e) => setBiggestGoal(e.target.value)} rows={3} className="w-full mt-1 bg-background border border-border rounded-md px-3 py-2 text-foreground text-sm resize-none focus:border-interactive focus:ring-1 focus:ring-interactive focus:outline-none transition-colors" placeholder="e.g. Grow Spotify streams, build a fanbase, release a project" />
              </div>
              <Button onClick={handleGenerate} disabled={generating || !artistName || !genre || !biggestGoal} className="w-full font-bebas text-lg tracking-wider h-12">
                {generating ? (
                  <><Sparkles className="w-5 h-5 mr-2 animate-spin" />GENERATING...</>
                ) : (
                  <><Sparkles className="w-5 h-5 mr-2" />GENERATE 30-DAY PLAN</>
                )}
              </Button>
            </div>

            {plan && (
              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="bg-card border border-primary/30 rounded-lg p-6 space-y-4">
                <div className="flex justify-between items-center">
                  <h2 className="font-bebas text-2xl text-foreground tracking-wider">YOUR PLAN</h2>
                  <Button variant="outline" size="sm" onClick={handleDownloadPDF} className="font-mono text-xs">
                    <Download className="w-3.5 h-3.5 mr-1" /> Download PDF
                  </Button>
                </div>
                <pre className="whitespace-pre-wrap text-sm text-foreground font-barlow leading-relaxed">{plan}</pre>
              </motion.div>
            )}
          </div>
        )}
      </div>
      <Footer />
    </div>
  );
};

export default Strategy;
